// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4LwY9CW9bB0YsROcKnyCQrWauSpfsnps',
    appId: '1:119673587074:web:3e3d03a17acc0946b1bb9b',
    messagingSenderId: '119673587074',
    projectId: 'todquest-3523c',
    authDomain: 'todquest-3523c.firebaseapp.com',
    storageBucket: 'todquest-3523c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNtheC4LYYJmv13YthGOQZeDORXDVv8Wg',
    appId: '1:119673587074:android:ec7fd1e0caf8ca84b1bb9b',
    messagingSenderId: '119673587074',
    projectId: 'todquest-3523c',
    storageBucket: 'todquest-3523c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDA32mqXBxE0HR6nJ7piiB0M7bMbV-fHw',
    appId: '1:119673587074:ios:2fa8efaaab8987a1b1bb9b',
    messagingSenderId: '119673587074',
    projectId: 'todquest-3523c',
    storageBucket: 'todquest-3523c.appspot.com',
    iosClientId: '119673587074-7nmfcfcq5lldse35rhmthtq8v386cau1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDA32mqXBxE0HR6nJ7piiB0M7bMbV-fHw',
    appId: '1:119673587074:ios:2fa8efaaab8987a1b1bb9b',
    messagingSenderId: '119673587074',
    projectId: 'todquest-3523c',
    storageBucket: 'todquest-3523c.appspot.com',
    iosClientId: '119673587074-7nmfcfcq5lldse35rhmthtq8v386cau1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todquest',
  );
}
